GRANT ALL ON ALL TABLES IN SCHEMA data TO etl;
GRANT USAGE ON SCHEMA data TO etl;

GRANT ALL ON ALL TABLES IN SCHEMA etl TO etl;
GRANT USAGE ON SCHEMA etl TO etl;

GRANT ALL ON ALL TABLES IN SCHEMA schedule TO etl;
GRANT USAGE ON SCHEMA schedule TO etl;

GRANT ALL ON ALL TABLES IN SCHEMA social TO etl;
GRANT USAGE ON SCHEMA social TO etl;

GRANT ALL ON ALL TABLES IN SCHEMA social_stat TO etl;
GRANT USAGE ON SCHEMA social_stat TO etl;

GRANT ALL ON ALL TABLES IN SCHEMA crm TO etl;
GRANT USAGE ON SCHEMA crm TO etl;
