CREATE DATABASE social
    WITH OWNER = etl;

CREATE SCHEMA schedule AUTHORIZATION etl;
GRANT ALL ON ALL TABLES IN SCHEMA schedule TO etl;
GRANT USAGE ON SCHEMA schedule TO etl;

CREATE SCHEMA stat AUTHORIZATION etl;
GRANT ALL ON ALL TABLES IN SCHEMA stat TO etl;
GRANT ALL ON stat.friends_online_stat TO etl;
GRANT USAGE ON SCHEMA stat TO etl;

GRANT ALL ON ALL TABLES IN SCHEMA social TO etl;


CREATE SCHEMA data AUTHORIZATION etl;
GRANT ALL ON ALL TABLES IN SCHEMA data TO etl;
GRANT USAGE ON SCHEMA data TO etl;